# Generated by Django 5.1.4 on 2024-12-12 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrators', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='administrator',
            old_name='adminstrator_id',
            new_name='administrator_id',
        ),
    ]
